{
  "hash": "6482e422ead69d5493ad7868e6624fa7",
  "result": {
    "engine": "knitr",
    "markdown": "# Cross Correlation\n\n\n::: {.cell}\n\n:::\n\n\n## Big Idea\nHere we extend the concept of the autocorrelation function to a bivariate case of how `y` might be correlated with lagged values of `x`.\n\n## Reading\nHave a look at Chapter three from @Cowpertwait2009. It's OK to skim the readings in this book. It's not a great book for our purposes as many of you haven't taken linear algebra and the book occasionally goes that way. But it's useful to hum your way through the chapter nonetheless.\n\n## Packages\nI'll use `forecast` [@R-forecast] as well as tidyverse [@R-tidyverse] syntax. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(forecast)\n```\n:::\n\n\n## Lags\nHere is a quick primer on different ways of lagging data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 10\nx <- ts(rnorm(n))\nx\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTime Series:\nStart = 1 \nEnd = 10 \nFrequency = 1 \n [1]  0.079854780  0.233410688  0.107206736  1.150652223  0.903326353\n [6] -0.965635624 -0.146067990 -0.559301795 -0.214952105  0.001970085\n```\n\n\n:::\n\n```{.r .cell-code}\n# v1: Lag by hand\nxLag_v1 <- ts(c(NA,x[-n]))\n# v2: use stats::lag (\"little el lag\")\n# Note the sign of k: negative k starts later.\nxLag_v2 <- stats::lag(x, k = -1)\nxLag_v2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTime Series:\nStart = 2 \nEnd = 11 \nFrequency = 1 \n [1]  0.079854780  0.233410688  0.107206736  1.150652223  0.903326353\n [6] -0.965635624 -0.146067990 -0.559301795 -0.214952105  0.001970085\n```\n\n\n:::\n\n```{.r .cell-code}\n# v3: use Hmisc::Lag  (\"big el lag\")\n# Note that shift is specifies the number of observations \n# to be shifted to the right -- positive shift starts later.\nxLag_v3 <- Hmisc::Lag(x, shift = 1)\nxLag_v3\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTime Series:\nStart = 1 \nEnd = 10 \nFrequency = 1 \n [1]          NA  0.07985478  0.23341069  0.10720674  1.15065222  0.90332635\n [7] -0.96563562 -0.14606799 -0.55930180 -0.21495211\n```\n\n\n:::\n\n```{.r .cell-code}\n# ^^ This is the same behavior that dplyr::lag has. E.g.,\ndplyr::lag(c(x),n=1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1]          NA  0.07985478  0.23341069  0.10720674  1.15065222  0.90332635\n [7] -0.96563562 -0.14606799 -0.55930180 -0.21495211\n```\n\n\n:::\n\n```{.r .cell-code}\n# But dplyr::lag doesn't like ts objects, hence the c(x). \n# It's all gross to parse out, I know.\n\ntsp(xLag_v1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  1 10  1\n```\n\n\n:::\n\n```{.r .cell-code}\ntsp(xLag_v2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  2 11  1\n```\n\n\n:::\n\n```{.r .cell-code}\ntsp(xLag_v3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  1 10  1\n```\n\n\n:::\n\n```{.r .cell-code}\n# ts.union helps you see what's going on\nts.union(x,xLag_v1,xLag_v2,xLag_v3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTime Series:\nStart = 1 \nEnd = 11 \nFrequency = 1 \n              x     xLag_v1      xLag_v2     xLag_v3\n 1  0.079854780          NA           NA          NA\n 2  0.233410688  0.07985478  0.079854780  0.07985478\n 3  0.107206736  0.23341069  0.233410688  0.23341069\n 4  1.150652223  0.10720674  0.107206736  0.10720674\n 5  0.903326353  1.15065222  1.150652223  1.15065222\n 6 -0.965635624  0.90332635  0.903326353  0.90332635\n 7 -0.146067990 -0.96563562 -0.965635624 -0.96563562\n 8 -0.559301795 -0.14606799 -0.146067990 -0.14606799\n 9 -0.214952105 -0.55930180 -0.559301795 -0.55930180\n10  0.001970085 -0.21495211 -0.214952105 -0.21495211\n11           NA          NA  0.001970085          NA\n```\n\n\n:::\n:::\n\n\n\n## From ACF to CCF\nChapter 3 introduces cross-correlation in the context of forecasting. Here, we reinforce the idea with a simple example and tie it back to the concept of autocorrelation.\n\nAutocorrelation is the correlation of a variable with its own past values (e.g., $y_t$ with $y_{t-1}$). Cross-correlation extends this idea to two different time series, asking: how does $x_{t-k}$ relate to $y_t$?\n\nYou’re already used to the idea that you can correlate two variables $x$ and $y$, but you can also lag $x$ like we did for autocorrelation. For example, $y_t$ can be correlated to $x_{t-1}$, which we can implement like this: `cor(y[2:n], x[1:(n-1)])`.\n\nHere’s a toy example:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 100\nx <- rnorm(n)\ny <- c(0, x[-n]) + rnorm(n, sd = 0.5)\ncor(x, y) # doesn't correlate\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1149159\n```\n\n\n:::\n\n```{.r .cell-code}\ncor(x[1:(n-1)], y[2:n]) # correlates great!\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8908105\n```\n\n\n:::\n\n```{.r .cell-code}\nCcf(x, y) # the cross correlation plot\n```\n\n::: {.cell-output-display}\n![](06CrossCorrelation_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nBy hand, you can see that $\\text{cor}(x_{t-1}, y_t) = 0.891$, whereas $\\text{cor}(x_t, y_t) = 0.115$. We can view these correlations across multiple lags using the cross-correlation plot from `Ccf`. That function returns the correlation between $x_{t+k}$ and $y_t$ for various values of lag $k$.\n\nA positive lag on the plot means that **x is lagged behind y** (i.e., you're correlating earlier y-values with later x-values), while a negative lag means **x leads y** — and might be useful for forecasting.\n\nThis kind of lagged relationship is useful for **predictive modeling**, where we use past values of one variable to forecast the present (or future) values of another.\n\nThus, given a time series like $x_t$, we could forecast $y_t$ based on $x_{t-1}$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# lag x\nxLag <- c(0, x[-n])\n# note this does the same lag operation\nxLag <- dplyr::lag(x, n = 1, default = 0)\n\nlmY <- lm(y ~ xLag)\nplot(y, predict(lmY))\nabline(lmY, col = \"blue\")\n```\n\n::: {.cell-output-display}\n![](06CrossCorrelation_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nCross-correlation is commonly used to identify short-lag predictive relationships. This is common in economics (e.g., jobless claims leading GDP) and in environmental science — for instance, where river discharge might precede changes in turbidity, or phytoplankton peaks might precede zooplankton booms.\n\nAs with all time series correlations, beware of spurious relationships — especially when both series share strong seasonal or trend components.\n\n\n\n\n## How `Ccf()` Normalizes Correlations\n\nThe eagle-eyed among you will notice that the values from `Ccf` don't align exactly with what `cor` produces. For the detail oriented, here is the scoop.\n\nThe `ccf()` function in R computes cross-correlations that are normalized in a specific way. It uses the full-series mean and standard deviation for both variables, even when the number of overlapping points decreases at higher lags. This section shows what that means in practice and how to manually reproduce the `ccf()` result at lag 1.\n\nLet's create some data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 100\nx <- rnorm(n)\n\n# make y depend on lagged x (lag = 1)\ny <- 0.8 * c(0, x[1:(n-1)]) + rnorm(n, sd = 0.5)\n\n# Lagged vectors aligned for lag 1\nx_lag <- x[1:(n - 1)]\ny_trunc <- y[2:n]\n```\n:::\n\n\nWe construct `y` to depend on a lagged version of `x`, and use `0` as the first value to avoid introducing an `NA`.\n\nLet's get the correlation at lag one using `cor()`\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(x_lag, y_trunc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8302037\n```\n\n\n:::\n:::\n\n\nThis computes a standard Pearson correlation using only the overlapping values. It uses `n - 1` observations and calculates means and standard deviations from that subset.\n\nLet's compare that to what `ccf()` gives\n\n\n::: {.cell}\n\n```{.r .cell-code}\nccf_obj <- Ccf(x, y, lag.max = 10)\n```\n\n::: {.cell-output-display}\n![](06CrossCorrelation_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n\n```{.r .cell-code}\nccf_lag1 <- ccf_obj$acf[ccf_obj$lag == -1]\nccf_lag1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8253849\n```\n\n\n:::\n:::\n\n\nThat correlation at lag 1 from `ccf_lag1`  is **slightly different** from the result of `cor(x_lag, y_trunc)` (0.8302037). Why? Because `ccf()`:\n- Uses only `n - 1` data pairs at lag 1\n- But computes the mean and standard deviation using all `n` values from the full series of `x` and `y`\n\nThis ensures that correlation values at all lags are on the same scale.\n\nWe can manually reproduce what `ccf()` does\n\n\n::: {.cell}\n\n```{.r .cell-code}\nk <- 1  # lag\nnum <- sum((x_lag - mean(x)) * (y_trunc - mean(y)))        # numerator\ndenom <- (n - k) * sd(x) * sd(y)                           # denominator uses full-series SDs\nmanual_ccf <- num / denom\nmanual_ccf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8253849\n```\n\n\n:::\n:::\n\n\nThis manual calculation matches the value from `ccf()` exactly.\n\nYou might ask yourself: why  does this matter? Well, this normalization approach allows `ccf()` (and `acf()`) to produce values that are comparable across different lags, even as the number of overlapping pairs shrinks. It’s a subtle point, but crucial for accurate interpretation of time series correlations. And when lags get really large like in the autotrophs and heterotrophs example, it's worth understanding what happens under the hood.\n\n## Your work\nLook at the file `PhytoGrazersExp1.rds`. It contains data used in a mesocosm simulation. The `producers` time series shows relative biomass of phytoplankton while the `grazers` time series shows the zooplankton biomass. The times are indexed by `day`. \n\n\n::: {.cell}\n\n```{.r .cell-code}\npg <- readRDS(\"data/PhytoGrazersExp1.rds\")\n# make these wide data long\npgLong <- pg %>% pivot_longer(cols=-1)\n# and make a nice ggplot\nggplot(pgLong,aes(x=day,y=value,color=name)) +\n  geom_line() +\n  geom_smooth(se = FALSE) +\n  labs(y=\"Relative biomass\",\n       x=\"Number of days from start of experiment\")\n```\n\n::: {.cell-output-display}\n![](06CrossCorrelation_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nIt seems clear that there is an offset between the two series. Just eyeballing it, it looks like there is a four to six week lag between the grazers and producers. Use cross correlation and see if you can determine the lagged relationship more specifically. \n\nThe file `PhytoExp2.rds` shows you just the phytoplankton from another experiment. Can you forecast the grazers over that time period? That is, show how you can use the lagged relationship between producers and grazers you found above to model the grazers in `PhytoExp2.rds`.\n\n\n### Write Up and Reflect\nPass in a R Markdown doc with your analysis. Leave all code visible, although you may quiet messages and warnings if desired. Turn in your knitted html. The last section of your document should include a reflection where you explain how it all went. What triumphs did you have? What is still confusing?\n\n",
    "supporting": [
      "06CrossCorrelation_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}