name: Update data.zip

on:
  push:
    paths:
      - 'data/**'

permissions:
  contents: write

jobs:
  zipdata:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create zip
        run: zip -r data.zip data

      - name: Commit zip
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data.zip
          git diff --staged --quiet || git commit -m "Update data.zip"
          git pull --rebase origin main
          git push
                    